### PR TITLE
fix conflicting `back` on callback

### PR DESCRIPTION
**Pull request by AsmSafone**
fix for conflicting back with https://github.com/UsergeTeam/Userge/blob/a114018cf26ce3a7dd7133baa6f4b847b46130f5/userge/plugins/builtin/help/__main__.py#L169

### CODE REVIEW

**Comment by Krishna-Singhal** [comment]
FIx Deepsource to get this PR merged

**Comment by AsmSafone** [comment]
> Fix Deepsource to get this PR merged

okay, btw the deepsource issue on others plugin files not on video_chat plugin :D

**Comment by Krishna-Singhal** [comment]
> okay, btw the deepsource issue on others plugin files not on video_chat plugin :D

yeah i know

**Comment by AsmSafone** [comment]
> > okay, btw the deepsource issue on others plugin files not on video_chat plugin :D
> 
> yeah i know

hmm, i m closing it cz it messed up. check this [pr](https://github.com/UsergeTeam/Userge-Plugins/pull/257).

**Pull request closed without merging**
