### PR TITLE
Removed bot_stamp 😄

### PR DESCRIPTION
**Pull request by rowdy-hero**

### CODE REVIEW

**Comment by Phyco-Ninja** [comment]
[Line 81](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L81) and [Line 87](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L87) are doing same thing i suppose 🤔....

You can use [message.reply_sticker()](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L89)

Try using [await saved.delete()](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L95)

[Please check for input_str first, Current check can cause bug.](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L45)
Eg: Suppose below is a conversation. 
1. Hey
2. .sticker Hello
1. Gets reply of sticker with text "Hey".

**Comment by Harsh-br0** [comment]
By the way 👀 , where is pep8 (－－〆)

**Comment by Phyco-Ninja** [comment]
> By the way  , where is pep8 (－－〆)

I'm PeP8 lelz😂

**Comment by rowdy-hero** [comment]
> By the way  , where is pep8 (－－〆)

There is no error from pep8 😒😒

**Comment by rowdy-hero** [comment]
> [Line 81](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L81) and [Line 87](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L87) are doing same thing i suppose ....
> 
> You can use [message.reply_sticker()](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L89)
> 
> Try using [await saved.delete()](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L95)
> 
> [Please check for input_str first, Current check can cause bug.](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L45)
> Eg: Suppose below is a conversation.
> 
> 1. Hey
> 2. .sticker Hello
> 3. Gets reply of sticker with text "Hey".



> [Line 81](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L81) and [Line 87](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L87) are doing same thing i suppose ....
> 
> You can use [message.reply_sticker()](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L89)
> 
> Try using [await saved.delete()](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L95)
> 
> [Please check for input_str first, Current check can cause bug.](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L45)
> Eg: Suppose below is a conversation.
> 
> 1. Hey
> 2. .sticker Hello
> 3. Gets reply of sticker with text "Hey".

First of all, line 81 and line 87 are diff, line 81 send inline_bot_result and line 87 get_messages()
I tried, it can't send without get_messages() 👀

Second , if message.reply_to_message then it will not work ig 🤔
And last , can u explain in 100-200 words, what's the bug in that line 😅

**Comment by Phyco-Ninja** [comment]
👀

**Comment by rowdy-hero** [comment]
> [Line 81](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L81) and [Line 87](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L87) are doing same thing i suppose ....
> 
> You can use [message.reply_sticker()](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L89)
> 
> Try using [await saved.delete()](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L95)
> 
> [Please check for input_str first, Current check can cause bug.](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L45)
> Eg: Suppose below is a conversation.
> 
> 1. Hey
> 2. .sticker Hello
> 3. Gets reply of sticker with text "Hey"

[Answered](https://github.com/UsergeTeam/Userge-Plugins/pull/84#issuecomment-659441297) to all questions successfully, now there is no error , cheers beers 😂😂

**Comment by Phyco-Ninja** [comment]
You can get results without get_messages() have u tried printing json output of saved in line 81.
U don't get point what I'm saying. Do i have to spoon feed and tell everything in details??

**Comment by rowdy-hero** [comment]
> You can get results without get_messages() have u tried printing json output of saved in line 81.
> U don't get point what I'm saying. Do i have to spoon feed and tell everything in details??

If you can't tell in detail, cuz of spoon feed then how u commented on PR, now u dosen't get any spoon feeding 🤔
And i don't know what u wanna say 🤷

**Comment by Phyco-Ninja** [comment]
> > You can get results without get_messages() have u tried printing json output of saved in line 81.
> > U don't get point what I'm saying. Do i have to spoon feed and tell everything in details??
> 
> If you can't tell in detail, cuz of spoon feed then how u commented on PR, now u dosen't get any spoon feeding 
> And i don't know what u wanna say

Check tag in group and get it what I'm saying

**Comment by Phyco-Ninja** [comment]
Lets do in practical

**Comment by Phyco-Ninja** [comment]
> > [Line 81](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L81) and [Line 87](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L87) are doing same thing i suppose ....
> > You can use [message.reply_sticker()](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L89)
> > Try using [await saved.delete()](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L95)
> > [Please check for input_str first, Current check can cause bug.](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L45)
> > Eg: Suppose below is a conversation.
> > 
> > 1. Hey
> > 2. .sticker Hello
> > 3. Gets reply of sticker with text "Hey".
> 
> First of all, line 81 and line 87 are diff, line 81 send inline_bot_result and line 87 get_messages()
> I tried, it can't send without get_messages() 
> 
> Second , if message.reply_to_message then it will not work ig 
> And last , can u explain in 100-200 words, what's the bug in that line

Okay Assuming you are tooo much fresh to these things lemme give some tooo much deeep explanation:

1. *Line 81 & Line 87* Both have similar json output. And i dunno why u thing u can't get same output from just by assigning ```saved```. 
That saved that u assigned in Line 81 can do the work but i dunno why you intended to use get_messages() and get same json output. Which caused repetition + you misused resources.
Just an assumption but your way of retrieving message felt same as what nana-Remix did. 

2. Why to use message.reply_sticker()? This will remove one variable chat_id which you are using currently. 

3. Same goes for await saved.delete() let me continue in case u still can't get. delete() requires a message object which u have already passed in line 81 which can be used Instead of calling userge.delete_messages()

4. Forth Issue was a Python fundamental, dunno why u didn't get it. Let me make it clear:
Below is sample of your code:
1. if replied:
2.    text = replied.text
3. else:
4.    text = message.input_str

Assume I gave someone with .sticker reply without text input, code works fine. 
Now i gave text input without reply, code still works fine. No issue so far. 
Problem comes when i gave a reply + a text input as per correct code it will just take reply input first intead of my input text (that was intended) if you still can't get. Lets make it more clear. 

It's works line whoever comes first is taken first. Since message went as a reply code will take input of replied text first and ignore that else statement... 

Can't explain further. If you Still can't get, then i dunno. Maybe Fuck it. Ignore my message 🤔

**Comment by Phyco-Ninja** [comment]
Hope it doesn't look rude. I'm very bad at explaining.

**Comment by rowdy-hero** [comment]
> > > [Line 81](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L81) and [Line 87](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L87) are doing same thing i suppose ....
> > > You can use [message.reply_sticker()](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L89)
> > > Try using [await saved.delete()](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L95)
> > > [Please check for input_str first, Current check can cause bug.](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L45)
> > > Eg: Suppose below is a conversation.
> > > 
> > > 1. Hey
> > > 2. .sticker Hello
> > > 3. Gets reply of sticker with text "Hey".
> > 
> > 
> > First of all, line 81 and line 87 are diff, line 81 send inline_bot_result and line 87 get_messages()
> > I tried, it can't send without get_messages()
> > Second , if message.reply_to_message then it will not work ig
> > And last , can u explain in 100-200 words, what's the bug in that line
> 
> Okay Assuming you are tooo much fresh to these things lemme give some tooo much deeep explanation:
> 
> 1. _Line 81 & Line 87_ Both have similar json output. And i dunno why u thing u can't get same output from just by assigning `saved`.
>    That saved that u assigned in Line 81 can do the work but i dunno why you intended to use get_messages() and get same json output. Which caused repetition + you misused resources.
>    Just an assumption but your way of retrieving message felt same as what nana-Remix did.
> 2. Why to use message.reply_sticker()? This will remove one variable chat_id which you are using currently.
> 3. Same goes for await saved.delete() let me continue in case u still can't get. delete() requires a message object which u have already passed in line 81 which can be used Instead of calling userge.delete_messages()
> 4. Forth Issue was a Python fundamental, dunno why u didn't get it. Let me make it clear:
>    Below is sample of your code:
> 5. if replied:
> 6. text = replied.text
> 7. else:
> 8. text = message.input_str
> 
> Assume I gave someone with .sticker reply without text input, code works fine.
> Now i gave text input without reply, code still works fine. No issue so far.
> Problem comes when i gave a reply + a text input as per correct code it will just take reply input first intead of my input text (that was intended) if you still can't get. Lets make it more clear.
> 
> It's works line whoever comes first is taken first. Since message went as a reply code will take input of replied text first and ignore that else statement...
> 
> Can't explain further. If you Still can't get, then i dunno. Maybe Fuck it. Ignore my message

I think I have to close PR 😔, it hurts you ig 🤧

**Comment by rowdy-hero** [comment]
> > > [Line 81](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L81) and [Line 87](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L87) are doing same thing i suppose ....
> > > You can use [message.reply_sticker()](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L89)
> > > Try using [await saved.delete()](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L95)
> > > [Please check for input_str first, Current check can cause bug.](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L45)
> > > Eg: Suppose below is a conversation.
> > > 
> > > 1. Hey
> > > 2. .sticker Hello
> > > 3. Gets reply of sticker with text "Hey".
> > 
> > 
> > First of all, line 81 and line 87 are diff, line 81 send inline_bot_result and line 87 get_messages()
> > I tried, it can't send without get_messages()
> > Second , if message.reply_to_message then it will not work ig
> > And last , can u explain in 100-200 words, what's the bug in that line
> 
> Okay Assuming you are tooo much fresh to these things lemme give some tooo much deeep explanation:
> 
> 1. _Line 81 & Line 87_ Both have similar json output. And i dunno why u thing u can't get same output from just by assigning `saved`.
>    That saved that u assigned in Line 81 can do the work but i dunno why you intended to use get_messages() and get same json output. Which caused repetition + you misused resources.
>    Just an assumption but your way of retrieving message felt same as what nana-Remix did.
> 2. Why to use message.reply_sticker()? This will remove one variable chat_id which you are using currently.
> 3. Same goes for await saved.delete() let me continue in case u still can't get. delete() requires a message object which u have already passed in line 81 which can be used Instead of calling userge.delete_messages()
> 4. Forth Issue was a Python fundamental, dunno why u didn't get it. Let me make it clear:
>    Below is sample of your code:
> 5. if replied:
> 6. text = replied.text
> 7. else:
> 8. text = message.input_str
> 
> Assume I gave someone with .sticker reply without text input, code works fine.
> Now i gave text input without reply, code still works fine. No issue so far.
> Problem comes when i gave a reply + a text input as per correct code it will just take reply input first intead of my input text (that was intended) if you still can't get. Lets make it more clear.
> 
> It's works line whoever comes first is taken first. Since message went as a reply code will take input of replied text first and ignore that else statement...
> 
> Can't explain further. If you Still can't get, then i dunno. Maybe Fuck it. Ignore my message

So what you want, input_str, with reply and reply with input_str
How third statement possible, it takes only replied text na 🤔
NO MORE CONVERSATION HERE , COME ON #OT

**Comment by Harsh-br0** [comment]
> Hope it doesn't look rude. I'm very bad at explaining.

@Phyco-Ninja nupe 
enough and resourcefully explained buddy (¯―¯٥)

**Comment by Harsh-br0** [comment]
> > > [Line 81](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L81) and [Line 87](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L87) are doing same thing i suppose ....
> > > You can use [message.reply_sticker()](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L89)
> > > Try using [await saved.delete()](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L95)
> > > [Please check for input_str first, Current check can cause bug.](https://github.com/rowdy-hero/Userge-Plugins/blob/patch-3/plugins/animesticker.py#L45)
> > > Eg: Suppose below is a conversation.
> > > 
> > > 1. Hey
> > > 2. .sticker Hello
> > > 3. Gets reply of sticker with text "Hey".
> > 
> > 
> > First of all, line 81 and line 87 are diff, line 81 send inline_bot_result and line 87 get_messages()
> > I tried, it can't send without get_messages()
> > Second , if message.reply_to_message then it will not work ig
> > And last , can u explain in 100-200 words, what's the bug in that line
> 
> Okay Assuming you are tooo much fresh to these things lemme give some tooo much deeep explanation:
> 
> 1. _Line 81 & Line 87_ Both have similar json output. And i dunno why u thing u can't get same output from just by assigning `saved`.
>    That saved that u assigned in Line 81 can do the work but i dunno why you intended to use get_messages() and get same json output. Which caused repetition + you misused resources.
>    Just an assumption but your way of retrieving message felt same as what nana-Remix did.
> 2. Why to use message.reply_sticker()? This will remove one variable chat_id which you are using currently.
> 3. Same goes for await saved.delete() let me continue in case u still can't get. delete() requires a message object which u have already passed in line 81 which can be used Instead of calling userge.delete_messages()
> 4. Forth Issue was a Python fundamental, dunno why u didn't get it. Let me make it clear:
>    Below is sample of your code:
> 5. if replied:
> 6. text = replied.text
> 7. else:
> 8. text = message.input_str
> 
> Assume I gave someone with .sticker reply without text input, code works fine.
> Now i gave text input without reply, code still works fine. No issue so far.
> Problem comes when i gave a reply + a text input as per correct code it will just take reply input first intead of my input text (that was intended) if you still can't get. Lets make it more clear.
> 
> It's works line whoever comes first is taken first. Since message went as a reply code will take input of replied text first and ignore that else statement...
> 
> Can't explain further. If you Still can't get, then i dunno. Maybe Fuck it. Ignore my message

If you would guide me like this 👀
 maybe userge-plugins got flooded earlier (・・;)

still you didn't (－－〆)

**Pull request merged**
