### PR TITLE
≧ω≦ sticklet

### PR DESCRIPTION
**Pull request by Phyco-Ninja**
ʕ•ε•ʔ Sticklet for Userge, Uses Random Fonts extracted from a Channel and then creates text sticker ^ω^

### CODE REVIEW

**Comment by rking32** [comment]
why git bot didn't work 🤔

**Comment by Phyco-Ninja** [comment]
Dunno sar 🤔 ,, :(

**Comment by rking32** [comment]
sad

**Comment by rking32** [comment]
now working 😐

**Comment by Phyco-Ninja** [comment]
Wtf 😐

**Pull request merged**
