### PR TITLE
remove custom thumbnail feature 😅

### PR DESCRIPTION
**Pull request by rowdy-hero**

### CODE REVIEW

**Comment by UdaySriHarsha** [comment]
bro its the best feature why removing

**Comment by Phyco-Ninja** [comment]
[Read This?](https://github.com/UsergeTeam/Userge-Plugins/issues?q=is%3Aissue+is%3Aclosed)

**Comment by rowdy-hero** [comment]
> [Read This?](https://github.com/UsergeTeam/Userge-Plugins/issues/32)

But why you offline at that time, everyone said that , remove this feature , need imdb thumbnail not custom

**Comment by Harsh-br0** [comment]
> [Read This?](https://github.com/UsergeTeam/Userge-Plugins/issues/32)

@Phyco-Ninja  Means , thumbnail stucks (・・;)

**Comment by rowdy-hero** [comment]
> bro its the best feature why removing

And you also there, saying that I also getting custom thumbnail , [see this](https://t.me/usergeot/365599) @UdaySriHarsha 
Everyome saying that remove that custom thumbnail feature , that why I create pull 😅

**Comment by Phyco-Ninja** [comment]
> > [Read This?](https://github.com/UsergeTeam/Userge-Plugins/issues/32)
> 
> But why you offline at that time, everyone said that , remove this feature , need imdb thumbnail not custom

I can't be online all the time at telegram. For now let it be . I dunno when this update was pushed no one objected on it. Although I also didn't want customs thumbnails. 
Now if u remove it someone else will pop up with demand of custom thumbs. I dunno. Hmmm, i was already going to do some fixes in imdb and memify for customizations. So if u want i can add up a fix for this. 🤔

**Comment by Phyco-Ninja** [comment]
> > [Read This?](https://github.com/UsergeTeam/Userge-Plugins/issues/32)
> 
> @Phyco-Ninja Means , thumbnail stucks (・・;)

And u are telling this now? Dunno WTF is wrong with everyone.

**Comment by Phyco-Ninja** [comment]
@rowdy-hero for now just rename path of thumb and revert all deletions. This patch will work for now

**Comment by rowdy-hero** [comment]
> > > [Read This?](https://github.com/UsergeTeam/Userge-Plugins/issues/32)
> > 
> > 
> > But why you offline at that time, everyone said that , remove this feature , need imdb thumbnail not custom
> 
> I can't be online all the time at telegram. For now let it be . I dunno when this update was pushed no one objected on it. Although I also didn't want customs thumbnails.
> Now if u remove it someone else will pop up with demand of custom thumbs. I dunno. Hmmm, i was already going to do some fixes in imdb and memify for customizations. So if u want i can add up a fix for this.

Hmm, this is good, you can make or customize, I will close this PR if you change imdb after closing this 🤷

**Pull request closed without merging**
