### PR TITLE
Adding fry.py and video support in deepfry.py

### PR DESCRIPTION
**Pull request by nub-boy**

### CODE REVIEW

**Comment by Phyco-Ninja** [comment]
Noice 🌚❤

**Comment by nub-boy** [comment]
> Noice

Need 1 more commit

**Comment by Phyco-Ninja** [comment]
Still u could have tried sending images in png format and stickers in webp format, bot can automatically convert stickers to sticker format and this would prevent white background occurrence when frying animated sticker.

**Comment by nub-boy** [comment]
Sorry, my bad 😅

**Pull request closed without merging**
