### PR TITLE
Updated Lyrics 

### PR DESCRIPTION
**Pull request by Phyco-Ninja**

### CODE REVIEW

**Comment by rking32** [comment]
@Phyco-Ninja what do you think about this

https://deepsource.io/gh/UsergeTeam/Userge-Plugins/run/5a4a9b36-06e4-4158-9721-09ba42731e21/python/PTC-W0016

**Comment by Phyco-Ninja** [comment]
> @Phyco-Ninja what do you think about this
> 
> https://deepsource.io/gh/UsergeTeam/Userge-Plugins/run/5a4a9b36-06e4-4158-9721-09ba42731e21/python/PTC-W0016

🤔 Dunno, that line takes lyrics as list and then with os.blabal it coverts it into lines

**Comment by rking32** [comment]
@Phyco-Ninja what about this
```python
lyrics = os.linesep.join(lyrics.splitlines())
```
`lyrics.splitlines()` return a list 🤔

**Comment by Phyco-Ninja** [comment]
> @Phyco-Ninja what about this
> 
> ```python
> lyrics = os.linesep.join(lyrics.splitlines())
> ```
> 
> `lyrics.splitlines()` return a list

Just `lyrics.splitlines()` give list

**Comment by rking32** [comment]
> > @Phyco-Ninja what about this
> > ```python
> > lyrics = os.linesep.join(lyrics.splitlines())
> > ```
> > 
> > 
> > `lyrics.splitlines()` return a list
> 
> Just `lyrics.splitlines()` give list

yes

**Pull request merged**
