### PR TITLE
Ascii Sticker Module

### PR DESCRIPTION
**Pull request by code-rgb**
add numpy, colour in requirements.

### CODE REVIEW

**Comment by UdaySriHarsha** [comment]
wut is this actually?

**Comment by Krishna-Singhal** [comment]
I already said millions of pep8 errors 😂😂😂

**Comment by Krishna-Singhal** [comment]
Still it will not delete full Download directory

**Comment by code-rgb** [comment]
deepsource fixes - https://github.com/UsergeTeam/Userge-Plugins/pull/102

**Pull request closed without merging**
