### PR TITLE
To avoid error when leaving private chats

### PR DESCRIPTION
**Pull request by lostb053**
When we leave private chats, we can no longer access our messages
message.delete() after userge.leave_chat() thus results in error
So delete first, then reply if exception which wont give error, dunno if edit reply/edit matters tho, still changed it
and leave later if no exception

### CODE REVIEW

**Comment by Harsh-br0** [comment]
> When we leave private chats, we can no longer access our messages
> message.delete() after userge.leave_chat() thus results in error
> So delete first, then reply if exception which wont give error, dunno if edit reply/edit matters tho, still changed it
> and leave later if no exception

Pro af

**Comment by lostb053** [comment]
nothing pro
first thing i do in every new fork
this time made a pull request
lol

**Comment by Harsh-br0** [comment]
> nothing pro
> first thing i do in every new fork
> this time made a pull request
> lol

Pro words

**Review by FayasNoushad — COMMENTED** [review]
Nice 👍

**Pull request merged**
