### PR TITLE
fix check

### PR DESCRIPTION
**Pull request by SpEcHiDe**

### CODE REVIEW

**Comment by rking32** [comment]
i think, error because of `os.environ.get("BOTSZ") = None`

**Comment by AlbertEinsteinTG** [comment]
> i think, error because of `os.environ.get("BOTSZ") = None`

idk why that happens but the plugins wrks fine in main repo

**Comment by AlbertEinsteinTG** [comment]
> > i think, error because of `os.environ.get("BOTSZ") = None`
> 
> idk why that happens but the plugins wrks fine in main repo

try my forked main repo.... ive added it in the admin folder and working without any issue

**Comment by rking32** [comment]
nice, but why closed ?

**Comment by SpEcHiDe** [comment]
@Krishna-Singhal 😂☺️☺️

**Comment by Krishna-Singhal** [comment]
> @Krishna-Singhal 😂☺️☺️

😞😞 i said already, I will commit in your pr

**Pull request closed without merging**
