### PR TITLE
Update transform.py

### PR DESCRIPTION
**Pull request by Krishna-Singhal**

### CODE REVIEW

**Comment by rking32** [comment]
@Krishna-Singhal don't hardcode commands
make seperate `on_cmd` decorator for each command
unless hard to manage these commands -> like `unload, load, enable, disable ...`

**Comment by Krishna-Singhal** [comment]
> @Krishna-Singhal don't hardcode commands
> make seperate `on_cmd` decorator for each command
> unless hard to manage these commands -> like `unload, load, enable, disable ...`

Code gonna lengthy 🌚

**Comment by Krishna-Singhal** [comment]
> > @Krishna-Singhal don't hardcode commands
> > make seperate `on_cmd` decorator for each command
> > unless hard to manage these commands -> like `unload, load, enable, disable ...`
> 
> Code gonna lengthy 🌚

Okay wait let me do it simple 😙

**Comment by rking32** [comment]
@Krishna-Singhal #hint 
try to find common methods in this plugin and make separate functions for them and call them when you want
sure it will compress your code :+1:

**Comment by Krishna-Singhal** [comment]
> @Krishna-Singhal #hint
> try to find common methods in this plugin and make separate functions for them and call them when you want
> sure it will compress your code 👍

I think this code is fine, if anyone want to manage like `unload`, `load`, `enable`, `disable ...`
[Check this](https://github.com/UsergeTeam/Userge-Plugins/blob/aa5a781ddbbc3aa4ab0d17ad0ca3e2a0b515660c/plugins/transform.py#L80), I setted name = `"mirror"` which helps to manage

**Comment by Krishna-Singhal** [comment]
> > @Krishna-Singhal #hint
> > try to find common methods in this plugin and make separate functions for them and call them when you want
> > sure it will compress your code 👍
> 
> I think this code is fine, if anyone want to manage like `unload`, `load`, `enable`, `disable ...`
> [Check this](https://github.com/UsergeTeam/Userge-Plugins/blob/aa5a781ddbbc3aa4ab0d17ad0ca3e2a0b515660c/plugins/transform.py#L80), I setted name = `"mirror"` which helps to manage

If this fine, merge this 🤷🏼🤷

**Comment by Krishna-Singhal** [comment]
> > > @Krishna-Singhal #hint
> > > try to find common methods in this plugin and make separate functions for them and call them when you want
> > > sure it will compress your code 👍
> > 
> > 
> > I think this code is fine, if anyone want to manage like `unload`, `load`, `enable`, `disable ...`
> > [Check this](https://github.com/UsergeTeam/Userge-Plugins/blob/aa5a781ddbbc3aa4ab0d17ad0ca3e2a0b515660c/plugins/transform.py#L80), I setted name = `"mirror"` which helps to manage
> 
> If this fine, merge this PR 🤷🏼🤷

**Comment by Krishna-Singhal** [comment]
> ok , then how invert works. you deleted that
> https://github.com/UsergeTeam/Userge-Plugins/blob/aa5a781ddbbc3aa4ab0d17ad0ca3e2a0b515660c/plugins/transform.py#L13-L16
> 
> 
> should it be `(ghost|invert)` like before ?

Yes, but cmd not working thats why I did it separate 🤔

**Comment by rking32** [comment]
try to add `name=" "` to that. should work

**Comment by rking32** [comment]
now it should work. did you try it ?

**Comment by Krishna-Singhal** [comment]
Letme  check in my fork repo 🤔

**Pull request merged**
