### PR TITLE
Create ascii.py

### PR DESCRIPTION
**Pull request by code-rgb**
deepsource fixes

### CODE REVIEW

**Comment by Krishna-Singhal** [comment]
[Not acceptable](https://github.com/UsergeTeam/Userge-Plugins/blob/2cb178a63b4977a4a135146fbbd9e60d28966a67/plugins/ascii.py#L89) relation of sam feature detected 😈

**Comment by Krishna-Singhal** [comment]
You Copying Not me, Let me Show You
[This](https://github.com/UsergeTeam/Userge-Plugins/blob/b885cd27ddbdd0ea3240bd9600c63745db20e32e/plugins/ascii.py#L26-L31] , [this](https://github.com/UsergeTeam/Userge-Plugins/blob/b885cd27ddbdd0ea3240bd9600c63745db20e32e/plugins/ascii.py#L49-L53), this](https://github.com/UsergeTeam/Userge-Plugins/blob/b885cd27ddbdd0ea3240bd9600c63745db20e32e/plugins/ascii.py#L59-L62) , [And you copied def function also 😒](https://github.com/UsergeTeam/Userge-Plugins/blob/b885cd27ddbdd0ea3240bd9600c63745db20e32e/plugins/ascii.py#L25), [and you didn't copy properly this line](https://github.com/UsergeTeam/Userge-Plugins/blob/b885cd27ddbdd0ea3240bd9600c63745db20e32e/plugins/ascii.py#L59), 👈 this will not response when user [replied video 😒](https://github.com/UsergeTeam/Userge-Plugins/blob/b885cd27ddbdd0ea3240bd9600c63745db20e32e/plugins/ascii.py#L28)

**Comment by code-rgb** [comment]
So what, Is referring from old modules not allowed? The main thing the module does is make Ascii sticker and your code helps but the whole module functionality don't depend on it.

**Comment by Krishna-Singhal** [comment]
> So what, Is referring from old modules not allowed? The main thing the module does is make Ascii sticker and your code helps but the whole module functionality don't depend on it.

Allowed but copy properly, now line 59 will create error 😒

**Comment by Krishna-Singhal** [comment]
> So what, Is referring from old modules not allowed? The main thing the module does is make Ascii sticker and your code helps but the whole module functionality don't depend on it.

In your opinion, what's the functionality of whole code 😒

**Pull request closed without merging**
