### PR TITLE
Create tweet.py 😉

### PR DESCRIPTION
**Pull request by Krishna-Singhal**

### CODE REVIEW

**Comment by rking32** [comment]
@Krishna-Singhal simplified a bit
can you check it now
is it ok, i can merge

**Comment by Krishna-Singhal** [comment]
> @Krishna-Singhal simplified a bit
> can you check it now
> is it ok, i can merge

Your simplified code is absolutely right sir, 😊
But if am I rights, [this def func](https://github.com/UsergeTeam/Userge-Plugins/blob/6196f1bc84aaa02b2b4658ee33a0695a95da1904/plugins/tweet.py#L168) needs 
return that 2 saved media 😅

**Comment by Krishna-Singhal** [comment]
> @Krishna-Singhal, Thanks for updating this PR.
> 
> * In the file [`plugins/tweet.py`](https://github.com/UsergeTeam/Userge-Plugins/blob/82be8c7821c05798a205c4759b4f8d6927ac9176/plugins/tweet.py):
> 
> > [Line 177:30](https://github.com/UsergeTeam/Userge-Plugins/blob/82be8c7821c05798a205c4759b4f8d6927ac9176/plugins/tweet.py#L177): [E999](https://duckduckgo.com/?q=pep8%20E999) SyntaxError: invalid syntax
> > [Line 178:5](https://github.com/UsergeTeam/Userge-Plugins/blob/82be8c7821c05798a205c4759b4f8d6927ac9176/plugins/tweet.py#L178): [E113](https://duckduckgo.com/?q=pep8%20E113) unexpected indentation

2 error of only   :   this is missing 😂😂😂

**Comment by Krishna-Singhal** [comment]
Now check @rking32 🤷🏼

**Comment by Krishna-Singhal** [comment]
Now check @rking32 🤷🏼
I used def func _deEmojify separately cuz of [this line](https://github.com/UsergeTeam/Userge-Plugins/blob/5c38e97630962c2e4487aa52e23c14328e257a6b/plugins/tweet.py#L178) gonna > 100

**Comment by rking32** [comment]
> > @Krishna-Singhal simplified a bit
> > can you check it now
> > is it ok, i can merge
> 
> Your simplified code is absolutely right sir, blush
> But if am I right, [this def func](https://github.com/UsergeTeam/Userge-Plugins/blob/6196f1bc84aaa02b2b4658ee33a0695a95da1904/plugins/tweet.py#L168) needs return that 2 saved media sweat_smile
> return CONVERTED_IMG, CONVERTED_STIKR
> 
> And also that api_url is incorrect, it will show error, I checked it. shrug
> Let me commit sweat_smile

no need of returning same photo and sticker, because they are already global.
we can access global vars directly. no need to return

**Comment by rking32** [comment]
no need of [this](https://github.com/UsergeTeam/Userge-Plugins/pull/103/commits/82be8c7821c05798a205c4759b4f8d6927ac9176) commit

**Comment by Krishna-Singhal** [comment]
> > > @Krishna-Singhal simplified a bit
> > > can you check it now
> > > is it ok, i can merge
> > 
> > 
> > Your simplified code is absolutely right sir, blush
> > But if am I right, [this def func](https://github.com/UsergeTeam/Userge-Plugins/blob/6196f1bc84aaa02b2b4658ee33a0695a95da1904/plugins/tweet.py#L168) needs return that 2 saved media sweat_smile
> > return CONVERTED_IMG, CONVERTED_STIKR
> > And also that api_url is incorrect, it will show error, I checked it. shrug
> > Let me commit sweat_smile
> 
> no need of returning same photo and sticker, because they are already global.
> we can access global vars directly. no need to return

Ah, yes

**Comment by Krishna-Singhal** [comment]
> no need of [this](https://github.com/UsergeTeam/Userge-Plugins/pull/103/commits/82be8c7821c05798a205c4759b4f8d6927ac9176) commit

I only assign first, then after use `text_` variable for easy understandable 🙂

**Comment by rking32** [comment]
> no need of [this](https://github.com/UsergeTeam/Userge-Plugins/pull/103/commits/82be8c7821c05798a205c4759b4f8d6927ac9176) commit

you can check this.
`text` and `username` will be `_deEmojify` before format with `api_url`
https://github.com/UsergeTeam/Userge-Plugins/blob/6196f1bc84aaa02b2b4658ee33a0695a95da1904/plugins/tweet.py#L169-L171

**Comment by Krishna-Singhal** [comment]
> > no need of [this](https://github.com/UsergeTeam/Userge-Plugins/pull/103/commits/82be8c7821c05798a205c4759b4f8d6927ac9176) commit
> 
> you can check this.
> `text` and `username` will be `_deEmojify` before format with `api_url`
> https://github.com/UsergeTeam/Userge-Plugins/blob/6196f1bc84aaa02b2b4658ee33a0695a95da1904/plugins/tweet.py#L169-L171

But this api_url format is incorrect, can we try this practically if working 🤷🏼

**Comment by rking32** [comment]
> > > no need of [this](https://github.com/UsergeTeam/Userge-Plugins/pull/103/commits/82be8c7821c05798a205c4759b4f8d6927ac9176) commit
> > 
> > 
> > you can check this.
> > `text` and `username` will be `_deEmojify` before format with `api_url`
> > https://github.com/UsergeTeam/Userge-Plugins/blob/6196f1bc84aaa02b2b4658ee33a0695a95da1904/plugins/tweet.py#L169-L171
> 
> But this api_url format is incorrect, can we try this practically if working 🤷🏼

yes, i checked before commit
worked perfectly with all commands

**Comment by Phyco-Ninja** [comment]
Use Twitter App keks

**Comment by Krishna-Singhal** [comment]
> > > > no need of [this](https://github.com/UsergeTeam/Userge-Plugins/pull/103/commits/82be8c7821c05798a205c4759b4f8d6927ac9176) commit
> > > 
> > > 
> > > you can check this.
> > > `text` and `username` will be `_deEmojify` before format with `api_url`
> > > https://github.com/UsergeTeam/Userge-Plugins/blob/6196f1bc84aaa02b2b4658ee33a0695a95da1904/plugins/tweet.py#L169-L171
> > 
> > 
> > But this api_url format is incorrect, can we try this practically if working 🤷🏼
> 
> yes, i checked before commit
> worked perfectly with all commands

Yeah, Working 😕👌🤘

**Comment by Krishna-Singhal** [comment]
> @Krishna-Singhal simplified a bit
> can you check it now
> is it ok, i can merge

Yes 👌🤘

**Pull request merged**
