### PR TITLE
Added Carbon Plugin

### PR DESCRIPTION
**Pull request by cyberboysumanjay**

### CODE REVIEW

**Comment by Harsh-br0** [comment]
Pep8 😓

**Comment by Harsh-br0** [comment]
@pep8speaks judge yourself first 😙

**Comment by Harsh-br0** [comment]
Why its not auto merging 🤔

**Comment by rking32** [comment]
finally :rofl:

**Comment by cyberboysumanjay** [comment]
A PR a day will improve my code formatting skills.

**Pull request merged**
