### PR TITLE
Maybe Fixed the OP Unicorn app bug.. LOL :)

### PR DESCRIPTION
**Pull request by prono69**

### CODE REVIEW

**Comment by Phyco-Ninja** [comment]
🌚Holy Sheet

**Comment by rking32** [comment]
@prono69 can you edit existing one

**Comment by prono69** [comment]
LOL

**Comment by prono69** [comment]
Remove old one and try it sar

**Comment by rking32** [comment]
@prono69 edit existing app.py 
it would be easy for you

**Comment by prono69** [comment]
Okay lemme just copi and paste

**Comment by prono69** [comment]
LOL

**Pull request closed without merging**
