### PR TITLE
Create google_photos.py

### PR DESCRIPTION
**Pull request by SpEcHiDe**

### CODE REVIEW

**Comment by UdaySriHarsha** [comment]
Nice @SpEcHiDe

**Comment by Phyco-Ninja** [comment]
Classic: ```No ones gonna help ya ``` 🤣🤣🤣🤣

**Comment by Krishna-Singhal** [comment]
3 synchronize, still failed 😂😂😂

**Comment by rking32** [comment]
thanks @SpEcHiDe 
i guess this is working :rofl: 
so merging :+1:

**Pull request merged**
