### PR TITLE
Added youtube thumbnail download support

### PR DESCRIPTION
**Pull request by FayasNoushad**
Added youtube thumbnail download support using `.ytthumb id` or `.ytthumb link`.

### CODE REVIEW

**Comment by rking32** [comment]
Hi @FayasNoushad, Thanks for your interest of this project. Next time update your branch before open pull request or create new branch per pull request. It will more clear than this and easy to review. Thanks you :)

**Comment by FayasNoushad** [comment]
> Hi @FayasNoushad, Thanks for your interest of this project. Next time update your branch before open pull request or create new branch per pull request. It will more clear than this and easy to review. Thanks you :)

Ok

**Comment by rking32** [comment]
By the way did you try `ytinfo` command. Seems like same thing for me.

**Comment by FayasNoushad** [comment]
> By the way did you try `ytinfo` command. Seems like same thing for me.

But its only thumbnail.

**Comment by FayasNoushad** [comment]
> By the way did you try `ytinfo` command. Seems like same thing for me.

Can I use `thumbnail` command?

**Comment by FayasNoushad** [comment]
Can you merge now?

**Comment by FayasNoushad** [comment]
> Hi @FayasNoushad, Thanks for your interest of this project. Next time update your branch before open pull request or create new branch per pull request. It will more clear than this and easy to review. Thanks you :)

I eill creating as new branch. Now closing this request.

**Pull request closed without merging**
